- name : terraform-ansible-portfolio-project
  hosts : portfolio
  become: yes
  tasks:
    - name: Installing nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: delete /usr/share/nginx/html/index.html file
      ansible.builtin.file:
        path: /usr/share/nginx/html/index.html
        state: absent
    - name: creating /usr/share/nginx/html/index.html file
      ansible.builtin.file:
        path: /usr/share/nginx/html/index.html
        state: touch
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ../Html/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'
